# -*- mode: ruby -*-
# vi: set ft=ruby :

IP="172.28.128.2"

# Esempio Vagrantfile 
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "private_network", ip: IP
  config.ssh.insert_key = false
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
end
